### PR TITLE
update readme to allow remote connections on jekyll

### PR DESCRIPTION
**Pull request by krichprollsch**
via docker

### CODE REVIEW

**Comment by krichprollsch** [comment]
It should fix your issue @themouette

**Comment by jmaupetit** [comment]
🤔 I don't get this. If you publish the container port on the same localhost's port, why would you need this? Is `docker` running inside a VM?

**Comment by krichprollsch** [comment]
Well, I guess exposing a port is just adding an iptable entry to forward to the container. So you keep the host ip.

```
$ sudo iptables -L
[sudo] Mot de passe de pierre : 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:4000

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere 
```

**Comment by themouette** [comment]
It should be something like remote address that does not resolve as
localhost.
Container has its own address, you Come from elsewhere: from container
point of view, you are not localhost!

Le 6 nov. 2016 6:47 PM, "Julien Maupetit" <notifications@github.com> a
écrit :

**Pull request merged**
